package Modelos;
// Generated 29/mai/2023 11:29:42 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Produtos produtos;
     private Date dataDoPedido;
     private String statusPedido;
     private String metodoDePagamento;

    public Pedidos() {
    }

    public Pedidos(int id, Cliente cliente, Produtos produtos, Date dataDoPedido, String statusPedido, String metodoDePagamento) {
       this.id = id;
       this.cliente = cliente;
       this.produtos = produtos;
       this.dataDoPedido = dataDoPedido;
       this.statusPedido = statusPedido;
       this.metodoDePagamento = metodoDePagamento;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Produtos getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Produtos produtos) {
        this.produtos = produtos;
    }
    public Date getDataDoPedido() {
        return this.dataDoPedido;
    }
    
    public void setDataDoPedido(Date dataDoPedido) {
        this.dataDoPedido = dataDoPedido;
    }
    public String getStatusPedido() {
        return this.statusPedido;
    }
    
    public void setStatusPedido(String statusPedido) {
        this.statusPedido = statusPedido;
    }
    public String getMetodoDePagamento() {
        return this.metodoDePagamento;
    }
    
    public void setMetodoDePagamento(String metodoDePagamento) {
        this.metodoDePagamento = metodoDePagamento;
    }




}


